name: Merge Autom√°tico

on:
  [pull_request]

permissions:
    contents: write
    pull-requests: write

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  MergeAutomatico:
    runs-on: ubuntu-latest
    steps:
        -   name: Aprovar PR
            uses: juliangruber/approve-pull-request-action@v1
            with:
                github-token: ${{ secrets.IDK_SECRET }}
                number: ${{env.PR_NUMBER}}

        # -   name: Mergear PR
        #     uses: juliangruber/merge-pull-request-action@v1
        #     with:
        #         github-token: ${{ secrets.GITHUB_TOKEN }}
        #         number: ${{env.PR_NUMBER}}
        #         method: merge


