name: Merge Autom√°tico

on:
  [pull_request]

permissions:
    contents: write
    pull-requests: write

jobs:
  MergeAutomatico:
    runs-on: ubuntu-latest
    steps:
        # -   name: Aprovar PR
        #     uses: juliangruber/approve-pull-request-action@v2
        #     with:
        #         github-token: ${{ secrets.GITHUB_TOKEN }}
        #         number: 1

        -   name: Mergear PR
            uses: juliangruber/merge-pull-request-action@v1
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                number: 1
                method: merge

