

name: Verificação de Build e Testes

on:
  [push]

jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Configurar JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'zulu'
  
        - name: Build Maven
          run: mvn -B package --file pom.xml

  Testes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configurar JDK 21 para testes
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Testes Unitários
        run: mvn test